# Generated by Django 5.2.4 on 2025-09-13 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('contact_info', models.BigIntegerField()),
                ('business_category', models.CharField(db_index=True, max_length=200)),
                ('registration_date', models.DateField(db_index=True)),
                ('status', models.CharField(max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lumo.merchant')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(db_index=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('base_currency', models.CharField(max_length=5)),
                ('created_at', models.DateField()),
                ('status', models.CharField(max_length=8)),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lumo.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('changed_at', models.DateTimeField()),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lumo.merchantstaff')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lumo.products')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_amount', models.IntegerField()),
                ('reason', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lumo.merchantstaff')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lumo.products')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lumo.products')),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('device_serial_id', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False)),
                ('model_type', models.CharField(max_length=100, null=True)),
                ('registration_date', models.DateField()),
                ('status', models.CharField(max_length=8)),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lumo.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='TerminalQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr_used', models.GenericIPAddressField()),
                ('date', models.DateField(db_index=True)),
                ('user_agent', models.TextField()),
                ('terminal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lumo.terminal')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reference', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100, null=True)),
                ('date_time', models.DateTimeField(db_index=True)),
                ('status', models.CharField(max_length=10)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lumo.customer')),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lumo.merchant')),
                ('terminal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lumo.terminal')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lumo.products')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lumo.transactions')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=65)),
                ('wallet_type', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField()),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lumo.customer')),
                ('merchant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lumo.merchant')),
            ],
        ),
        migrations.AddField(
            model_name='transactions',
            name='wallet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lumo.wallet'),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_type', models.CharField(max_length=100)),
                ('token_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('exchange_rate_token_usd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=6)),
                ('exchange_rate_usd_local_currency', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amount_local_currency', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(max_length=10)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lumo.transactions')),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lumo.wallet')),
            ],
        ),
    ]
