# Generated by Django 5.2.4 on 2025-09-23 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lumo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchantstaff',
            old_name='merchant_id',
            new_name='merchant',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='transaction_id',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='wallet_id',
            new_name='wallet',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='merchant_id',
            new_name='merchant',
        ),
        migrations.RenameField(
            model_name='terminal',
            old_name='merchant_id',
            new_name='merchant',
        ),
        migrations.RenameField(
            model_name='terminalquery',
            old_name='terminal_id',
            new_name='terminal',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='merchant_id',
            new_name='merchant',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='terminal_id',
            new_name='terminal',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='wallet_id',
            new_name='wallet',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='merchantstaff',
            name='user_id',
        ),
        migrations.AddField(
            model_name='merchant',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchantstaff',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lumo.customer'),
        ),
        migrations.AddField(
            model_name='products',
            name='image_url',
            field=models.URLField(default='/static/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='display_name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='contact_info',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='location',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='registration_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='status',
            field=models.CharField(default='Active', max_length=8),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='PrivyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privy_id', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privy_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='wallet',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='Lumo.privyprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lumo.privyprofile'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lumo.privyprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('profile', 'address')},
        ),
        migrations.CreateModel(
            name='SalesOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lumo.customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lumo.products')),
            ],
        ),
        migrations.AddField(
            model_name='payments',
            name='sales_orders',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Lumo.salesorders'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TransactionLineItem',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='wallet_type',
        ),
    ]
