# Generated by Django 5.2.4 on 2025-09-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lumo', '0002_rename_merchant_id_merchantstaff_merchant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='contact_info',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='business_category',
        ),
        migrations.AlterField(
            model_name='merchant',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
