# Generated by Django 5.2.6 on 2025-09-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lumo', '0003_rename_contact_info_merchant_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='registration_date',
            field=models.DateField(auto_now=True, db_index=True),
        ),
    ]
